[project]
name = "morphology-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dhg>=0.9.5",
    "dill>=0.4.1",
    "gymnasium[box2d]>=1.2.3",
    "notebook>=7.5.3",
    "pandas>=2.3.3",
]
